version: "3.8"

services:
  mongodb:
    image: mongo:5.0.2
    ports:
      - "27017:27017"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/myapp
    restart: unless-stopped
    volumes:
      - db:/data/db
  app:
    depends_on:
      - mongodb
    build: ./
    restart: unless-stopped
    env_file: 
      - ./config/dev.env
    environment:
      MONGODB_URL: mongodb://mongodb:27017/myapp
    ports:
      - 3000:3000
    stdin_open: true
    tty: true

volumes:
  db: